In [57]:
import pyodbc

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=MSI\SQLE22;"
    r"DATABASE=UFC;"
    r"Trusted_Connection=yes;"
)

print("CONNECTED")

CONNECTED

In [58]:
import pandas as pd 


query = 'select * from fight_details'

data = pd.read_sql(query,conn)

C:\Users\mplan\AppData\Local\Temp\ipykernel_20788\1035679361.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query,conn)

In [59]:
data.head(1)

,url,fighter1,fighter2,fighter1_sig_str,fighter2_sig_str,fighter1_sig_pct,fighter2_sig_pct,fighter1_head,fighter2_head,fighter1_body,...,fighter2_leg,fighter1_distance,fighter2_distance,fighter1_clinch,fighter2_clinch,fighter1_ground,fighter2_ground,fight_id,fighter1_id,fighter2_id
0,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,1 of 1,0 of 4,100%,0%,1 of 1,0 of 2,0 of 0,...,0 of 2,0 of 0,0 of 3,1 of 1,0 of 1,0 of 0,0 of 0,1,10.0,1.0

In [60]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8701 entries, 0 to 8700
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url                8701 non-null   str
 1   fighter1           8701 non-null   str
 2   fighter2           8701 non-null   str
 3   fighter1_sig_str   8673 non-null   str
 4   fighter2_sig_str   8673 non-null   str
 5   fighter1_sig_pct   8673 non-null   str
 6   fighter2_sig_pct   8673 non-null   str
 7   fighter1_head      8673 non-null   str
 8   fighter2_head      8673 non-null   str
 9   fighter1_body      8673 non-null   str
 10  fighter2_body      8673 non-null   str
 11  fighter1_leg       8673 non-null   str
 12  fighter2_leg       8673 non-null   str
 13  fighter1_distance  8673 non-null   str
 14  fighter2_distance  8673 non-null   str
 15  fighter1_clinch    8673 non-null   str
 16  fighter2_clinch    8673 non-null   str
 17  fighter1_ground    8673 non-null   str
 18  fighter2_ground    8673 non-null   str
 19  fight_id           8701 non-null   int64
 20  fighter1_id        8696 non-null   float64
 21  fighter2_id        8688 non-null   float64
dtypes: float64(2), int64(1), str(19)
memory usage: 1.5 MB

In [61]:
data.shape

(8701, 22)

In [62]:
data.isnull().sum()

url                   0
fighter1              0
fighter2              0
fighter1_sig_str     28
fighter2_sig_str     28
fighter1_sig_pct     28
fighter2_sig_pct     28
fighter1_head        28
fighter2_head        28
fighter1_body        28
fighter2_body        28
fighter1_leg         28
fighter2_leg         28
fighter1_distance    28
fighter2_distance    28
fighter1_clinch      28
fighter2_clinch      28
fighter1_ground      28
fighter2_ground      28
fight_id              0
fighter1_id           5
fighter2_id          13
dtype: int64

In [63]:
data = data.dropna()

In [64]:
data.head(1)

,url,fighter1,fighter2,fighter1_sig_str,fighter2_sig_str,fighter1_sig_pct,fighter2_sig_pct,fighter1_head,fighter2_head,fighter1_body,...,fighter2_leg,fighter1_distance,fighter2_distance,fighter1_clinch,fighter2_clinch,fighter1_ground,fighter2_ground,fight_id,fighter1_id,fighter2_id
0,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,1 of 1,0 of 4,100%,0%,1 of 1,0 of 2,0 of 0,...,0 of 2,0 of 0,0 of 3,1 of 1,0 of 1,0 of 0,0 of 0,1,10.0,1.0

In [65]:
## βλέπω ότι υπάρχει ποσοστο sig_str άρα θα μετατρέψω αυτό το ποσοστό σε δεκαδικο και θα κρατήσω απο όλα τα άλλα μόνο τα συνολικά χτυήματα που βρήκαν στόχο

In [66]:
def get_first(column):
    xs = []
    for i  in  data[column]:
        x,y = i.split('of')
        x.strip()
        xs.append(x)
    name = column + '_total'
    data[name] = xs


cols = [
    'fighter1_sig_str',
    'fighter2_sig_str',

    'fighter1_head',
    'fighter2_head',

    'fighter1_body',
    'fighter2_body',

    'fighter1_leg',
    'fighter2_leg',

    'fighter1_distance',
    'fighter2_distance',

    'fighter1_clinch',
    'fighter2_clinch',

    'fighter1_ground',
    'fighter2_ground',

]
for col in cols:
    get_first(col)

In [67]:
data.drop(columns = cols,inplace=True)
data.drop(columns = ['fighter1','fighter2','url'],inplace=True)

In [68]:
data['fighter1_percent_sign'] = (
    pd.to_numeric(
        data['fighter1_sig_pct'].str.replace('%', ''),
        errors='coerce'
    ) / 100
)

data['fighter2_percent_sign'] = (pd.to_numeric(data['fighter2_sig_pct'].str.replace('%',''),errors='coerce')/100)

In [69]:
data.head(1)

,fighter1_sig_pct,fighter2_sig_pct,fight_id,fighter1_id,fighter2_id,fighter1_sig_str_total,fighter2_sig_str_total,fighter1_head_total,fighter2_head_total,fighter1_body_total,...,fighter1_leg_total,fighter2_leg_total,fighter1_distance_total,fighter2_distance_total,fighter1_clinch_total,fighter2_clinch_total,fighter1_ground_total,fighter2_ground_total,fighter1_percent_sign,fighter2_percent_sign
0,100%,0%,1,10.0,1.0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,1.0,0.0

In [70]:
data.info()

<class 'pandas.DataFrame'>
Index: 8673 entries, 0 to 8700
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fighter1_sig_pct         8673 non-null   str
 1   fighter2_sig_pct         8673 non-null   str
 2   fight_id                 8673 non-null   int64
 3   fighter1_id              8673 non-null   float64
 4   fighter2_id              8673 non-null   float64
 5   fighter1_sig_str_total   8673 non-null   str
 6   fighter2_sig_str_total   8673 non-null   str
 7   fighter1_head_total      8673 non-null   str
 8   fighter2_head_total      8673 non-null   str
 9   fighter1_body_total      8673 non-null   str
 10  fighter2_body_total      8673 non-null   str
 11  fighter1_leg_total       8673 non-null   str
 12  fighter2_leg_total       8673 non-null   str
 13  fighter1_distance_total  8673 non-null   str
 14  fighter2_distance_total  8673 non-null   str
 15  fighter1_clinch_total    8673 non-null   str
 16  fighter2_clinch_total    8673 non-null   str
 17  fighter1_ground_total    8673 non-null   str
 18  fighter2_ground_total    8673 non-null   str
 19  fighter1_percent_sign    8641 non-null   float64
 20  fighter2_percent_sign    8622 non-null   float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.5 MB

In [71]:
data.head(1)

,fighter1_sig_pct,fighter2_sig_pct,fight_id,fighter1_id,fighter2_id,fighter1_sig_str_total,fighter2_sig_str_total,fighter1_head_total,fighter2_head_total,fighter1_body_total,...,fighter1_leg_total,fighter2_leg_total,fighter1_distance_total,fighter2_distance_total,fighter1_clinch_total,fighter2_clinch_total,fighter1_ground_total,fighter2_ground_total,fighter1_percent_sign,fighter2_percent_sign
0,100%,0%,1,10.0,1.0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,1.0,0.0

In [73]:
data = data.drop(columns = ['fighter1_sig_pct','fighter2_sig_pct'])

In [77]:
data.head(1)

,fight_id,fighter1_id,fighter2_id,fighter1_sig_str_total,fighter2_sig_str_total,fighter1_head_total,fighter2_head_total,fighter1_body_total,fighter2_body_total,fighter1_leg_total,fighter2_leg_total,fighter1_distance_total,fighter2_distance_total,fighter1_clinch_total,fighter2_clinch_total,fighter1_ground_total,fighter2_ground_total,fighter1_percent_sign,fighter2_percent_sign
0,1,10,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1.0,0.0

In [76]:
data['fighter1_id'] = (data['fighter1_id']).astype(int)
data['fighter2_id'] = (data['fighter2_id']).astype(int)

In [79]:
data = data.fillna(0)

In [80]:
data.isnull().sum()

fight_id                   0
fighter1_id                0
fighter2_id                0
fighter1_sig_str_total     0
fighter2_sig_str_total     0
fighter1_head_total        0
fighter2_head_total        0
fighter1_body_total        0
fighter2_body_total        0
fighter1_leg_total         0
fighter2_leg_total         0
fighter1_distance_total    0
fighter2_distance_total    0
fighter1_clinch_total      0
fighter2_clinch_total      0
fighter1_ground_total      0
fighter2_ground_total      0
fighter1_percent_sign      0
fighter2_percent_sign      0
dtype: int64

In [81]:
data.to_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\fight_details_training.csv',index=False)