In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests


print('ok')

ok

In [2]:
df1 = pd.read_csv('events.csv')
df1 = df1[['ID','event_url']]

In [5]:
df1.head(1)

    ID                                          event_url
0  773  http://ufcstats.com/event-details/9eedac48b497...

In [6]:
links = df1['event_url'].tolist()
ids = df1['ID'].tolist()

In [9]:
fights = []

for link in links:

    response = requests.get(link)

    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.select("tr.b-fight-details__table-row")

    event_name = soup.find(
        "span",
        class_="b-content__title-highlight"
    ).text.strip()

    for row in rows:

        fight_url = row.get("data-link")

        cells = row.find_all("td")

        if len(cells) < 10:
            continue

        fighters = cells[1].find_all("a")

        fighter_1 = fighters[0].text.strip() if len(fighters) > 0 else None
        fighter_2 = fighters[1].text.strip() if len(fighters) > 1 else None

        # stats
        kd = cells[2].text.strip()

        strikes = cells[3].text.strip()

        td = cells[4].text.strip()

        sub = cells[5].text.strip()

        # other info
        weight_class = cells[6].text.strip()

        method = cells[7].text.strip()

        round_ended = cells[8].text.strip()

        time = cells[9].text.strip()

        fights.append({

            "event_name": event_name,

            "fight_url": fight_url,

            "fighter_1": fighter_1,
            "fighter_2": fighter_2,

            "kd": kd,
            "strikes": strikes,
            "td": td,
            "sub": sub,

            "weight_class": weight_class,

            "method": method,

            "round": round_ended,

            "time": time
        })

print(fights[:5])

[{'event_name': 'UFC 328: Chimaev vs. Strickland', 'fight_url': 'http://ufcstats.com/fight-details/70f1621080b3435c', 'fighter_1': 'Sean Strickland', 'fighter_2': 'Khamzat Chimaev', 'kd': '0\n          \n\n            \n            0', 'strikes': '123\n\n          \n\n\n            \n            98', 'td': '0\n          \n\n            \n            9', 'sub': '0\n          \n\n            \n            0', 'weight_class': 'Middleweight', 'method': 'S-DEC', 'round': '5', 'time': '5:00'}, {'event_name': 'UFC 328: Chimaev vs. Strickland', 'fight_url': 'http://ufcstats.com/fight-details/c85b530861145935', 'fighter_1': 'Joshua Van', 'fighter_2': 'Tatsuro Taira', 'kd': '2\n          \n\n            \n            0', 'strikes': '131\n\n          \n\n\n            \n            55', 'td': '1\n          \n\n            \n            8', 'sub': '2\n          \n\n            \n            0', 'weight_class': 'Flyweight', 'method': 'KO/TKO\n\n      \n\n        Punches', 'round': '5', 'time': '1:32'}, {'event_name': 'UFC 328: Chimaev vs. Strickland', 'fight_url': 'http://ufcstats.com/fight-details/22ba4f1b0aafbf82', 'fighter_1': 'Alexander Volkov', 'fighter_2': 'Waldo Cortes Acosta', 'kd': '0\n          \n\n            \n            0', 'strikes': '88\n\n          \n\n\n            \n            54', 'td': '0\n          \n\n            \n            0', 'sub': '0\n          \n\n            \n            0', 'weight_class': 'Heavyweight', 'method': 'U-DEC', 'round': '3', 'time': '5:00'}, {'event_name': 'UFC 328: Chimaev vs. Strickland', 'fight_url': 'http://ufcstats.com/fight-details/845b8653f9cf839c', 'fighter_1': 'Sean Brady', 'fighter_2': 'Joaquin Buckley', 'kd': '0\n          \n\n            \n            0', 'strikes': '77\n\n          \n\n\n            \n            5', 'td': '4\n          \n\n            \n            0', 'sub': '0\n          \n\n            \n            0', 'weight_class': 'Welterweight', 'method': 'U-DEC', 'round': '3', 'time': '5:00'}, {'event_name': 'UFC 328: Chimaev vs. Strickland', 'fight_url': 'http://ufcstats.com/fight-details/1158a27a1a04b971', 'fighter_1': 'King Green', 'fighter_2': 'Jeremy Stephens', 'kd': '0\n          \n\n            \n            0', 'strikes': '57\n\n          \n\n\n            \n            5', 'td': '1\n          \n\n            \n            0', 'sub': '1\n          \n\n            \n            1', 'weight_class': 'Lightweight', 'method': 'SUB\n\n      \n\n        Rear Naked Choke', 'round': '1', 'time': '4:20'}]

In [10]:
len(fights)

8688

In [11]:
fights_df = pd.DataFrame(fights)

In [13]:
fights_df.head(1)

,event_name,fight_url,fighter_1,fighter_2,kd,strikes,td,sub,weight_class,method,round,time
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,0\n \n\n \n 0,123\n\n \n\n\n \n ...,0\n \n\n \n 9,0\n \n\n \n 0,Middleweight,S-DEC,5,5:00

In [ ]:
fights_df['fight_url'][0] #ok 
fights_df['fighter_1'][0] # ok
fights_df['fighter_2'][0] #ok 
fights_df['kd'][0] #ok 
fights_df['strikes'][0] # ok 
fights_df['td'][0] #ok
fights_df['sub'][0] # ok 
fights_df['weight_class'][0] #οκ
fights_df['method'][0]

'S-DEC'

In [29]:
# παρατηρώ ότι υπάρχει ανομοιμορφία και ότι πρέπει να χωρίσω τα στατσ ανα πέκτη , επομένως εδώ κάνω ένα τεστ και μετά πάω να το εφαρμόσω κανονικά

fighter1_kd = fights_df['kd'][0].replace('\n','')[:10].strip()
fighter2_kd = fights_df['kd'][0].replace('\n','')[-10:].strip()
print(fighter1_kd,fighter2_kd)

0 0

In [51]:
# για τα kds 

fighter1_kd = []
fighter2_kd = []


kds = fights_df['kd']
for kd in kds:
    fighter1_kd.append(kd.replace('\n','')[:10].strip())
    fighter2_kd.append(kd.replace('\n','')[-10:].strip())


# για τα strikes 

fighter1_strikes = []
fighter2_strikes = []


strikes = fights_df['strikes']
for strike in strikes:
    fighter1_strikes.append(strike.replace('\n','')[:10].strip())
    fighter2_strikes.append(strike.replace('\n','')[-10:].strip())

# gia to td 


fighter1_td = []
fighter2_td = []


tds = fights_df['td']
for td in tds:
    fighter1_td.append(td.replace('\n','')[:10].strip())
    fighter2_td.append(td.replace('\n','')[-10:].strip())

# gia to sub 

fighter1_sub = []
fighter2_sub = []


subs = fights_df['sub']
for sub in subs:
    fighter1_sub.append(sub.replace('\n','')[:10].strip())
    fighter2_sub.append(sub.replace('\n','')[-10:].strip())


fights_df['fighter1_kd'] = fighter1_kd
fights_df['fighter2_kd'] = fighter2_kd

fights_df['fighter1_strikes'] = fighter1_strikes
fights_df['fighter2_strikes'] = fighter2_strikes

fights_df['fighter1_td'] = fighter1_td
fights_df['fighter2_td'] = fighter2_td

fights_df['fighter1_sub'] = fighter1_sub
fights_df['fighter2_sub'] = fighter2_sub

In [ ]:
#σχεδόν έτοιμα μένει και η μέθοδος νίκης

In [69]:
methods_d = fights_df['method']
methods_d[:10]

0                                        S-DEC
1          KO/TKO\n\n      \n\n        Punches
2                                        U-DEC
3                                        U-DEC
4    SUB\n\n      \n\n        Rear Naked Choke
5            KO/TKO\n\n      \n\n        Punch
6        SUB\n\n      \n\n        Arm Triangle
7    SUB\n\n      \n\n        Rear Naked Choke
8    SUB\n\n      \n\n        Guillotine Choke
9                                        U-DEC
Name: method, dtype: str

In [76]:
methods_d = fights_df['method']
methods = []
for method in methods_d:
    methods.append(method.replace('\n','').replace('              ',' ').strip())

In [77]:
methods[:10]

['S-DEC',
 'KO/TKO Punches',
 'U-DEC',
 'U-DEC',
 'SUB Rear Naked Choke',
 'KO/TKO Punch',
 'SUB Arm Triangle',
 'SUB Rear Naked Choke',
 'SUB Guillotine Choke',
 'U-DEC']

In [78]:
fights_df['method'] = methods

In [79]:
fights_df.head(2)

,event_name,fight_url,fighter_1,fighter_2,kd,strikes,td,sub,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,0\n \n\n \n 0,123\n\n \n\n\n \n ...,0\n \n\n \n 9,0\n \n\n \n 0,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0
1,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,2\n \n\n \n 0,131\n\n \n\n\n \n ...,1\n \n\n \n 8,2\n \n\n \n 0,Flyweight,KO/TKO Punches,5,1:32,2,0,131,55,1,8,2,0

In [80]:
# όλα είναι οκ πάμε να ρίξουμε τις άχρηστες στήλες και να αναδιαμορφόσουμε το df

In [81]:
fights_df.drop(columns=['kd','strikes','td','sub'],inplace=True)

In [82]:
fights_df.head(1)

,event_name,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0

In [83]:
# τώρα θα βάλουμε id event σε κάθε αγώνα ώστε να επιτρέπετε αργότερα το join

In [84]:
events = pd.read_csv('events.csv')

In [85]:
events.head(2)

,ID,event_name,main_card,year,country,month,day,city,region,event_url
0,773,UFC 328: Chimaev vs. Strickland,1,2026,USA,May,9,Newark,New Jersey,http://ufcstats.com/event-details/9eedac48b497...
1,772,UFC Fight Night: Della Maddalena vs. Prates,0,2026,Australia,May,2,Perth,Western Australia,http://ufcstats.com/event-details/872b018076f8...

In [86]:
events = events[['event_name','ID']]
events.head(2)

                                    event_name   ID
0              UFC 328: Chimaev vs. Strickland  773
1  UFC Fight Night: Della Maddalena vs. Prates  772

In [87]:
df_test = fights_df.copy()

In [94]:
df_test = events.merge(df_test, on='event_name',how='left')

In [97]:
df_test['fight_url'][0]

'http://ufcstats.com/fight-details/70f1621080b3435c'

In [98]:
df_test = df_test.rename(columns={'ID': 'event_id'})
##fights = df_test[['event_id','fighter1','fighter2','weight_class','method','']]

In [96]:
df_test.shape, fights_df.shape

((8688, 17), (8688, 16))

In [ ]:
# και κάπου έδω μετά απο τυφλή επεξεργασία βλέπουμε ότι δεν έχουμε πάρει το πιο βασικό , ΤΟΝ ΝΙΚΙΤΗ  επομένως πάμε να τον πάρουμε και να κάνουμε ξανά μετά join
## γαμω το σπιτι μου 
##επειδή εκείδεν είναι ξεκάθαρο το html πρέπει να πάρουμε τον νικιτή απο το λινκ των details

In [101]:
len(links)

773

In [133]:
df_test.head(1)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0

In [138]:
df_test.to_csv('fights_temp.csv',index=False)

In [2]:
d  = pd.read_csv('fights_temp.csv')
d.head(2)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0
1,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Flyweight,KO/TKO Punches,5,1:32,2,0,131,55,1,8,2,0

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

new_links = d['fight_url'].dropna().unique()

headers = {"User-Agent": "Mozilla/5.0"}

session = requests.Session()
session.headers.update(headers)

results = []

for i, url in enumerate(new_links):

    try:
        r = session.get(url, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")

        names = soup.select(".b-fight-details__person-name")
        statuses = soup.select(".b-fight-details__person-status")

        if len(names) < 2 or len(statuses) < 2:
            continue

        fighter_1 = names[0].get_text(strip=True)
        fighter_2 = names[1].get_text(strip=True)

        status_1 = statuses[0].get_text(strip=True)
        status_2 = statuses[1].get_text(strip=True)

        if status_1 == "W":
            winner = fighter_1
        elif status_2 == "W":
            winner = fighter_2
        else:
            winner = None

        results.append({
            "fight_url": url,
            "winner": winner
        })

        print(f"{i+1}/{len(new_links)}")

        time.sleep(0.5)  

    except Exception as e:
        print("error:", url)
        time.sleep(2)
        continue


wins = pd.DataFrame(results, columns=['fight_url', 'winner'])

wins.to_csv('temp_wins.csv', index=False)

1/8688
2/8688
3/8688
4/8688
5/8688
6/8688
7/8688
8/8688
9/8688
10/8688
11/8688
12/8688
13/8688
14/8688
15/8688
16/8688
17/8688
18/8688
19/8688
20/8688
21/8688
22/8688
23/8688
24/8688
25/8688
26/8688
27/8688
28/8688
29/8688
30/8688
31/8688
32/8688
33/8688
34/8688
35/8688
36/8688
37/8688
38/8688
39/8688
40/8688
41/8688
42/8688
43/8688
44/8688
45/8688
46/8688
47/8688
48/8688
49/8688
50/8688
51/8688
52/8688
53/8688
54/8688
55/8688
56/8688
57/8688
58/8688
59/8688
60/8688
61/8688
62/8688
63/8688
64/8688
65/8688
66/8688
67/8688
68/8688
69/8688
70/8688
71/8688
72/8688
73/8688
74/8688
75/8688
76/8688
77/8688
78/8688
79/8688
80/8688
81/8688
82/8688
83/8688
84/8688
85/8688
86/8688
87/8688
88/8688
89/8688
90/8688
91/8688
92/8688
93/8688
94/8688
95/8688
96/8688
97/8688
98/8688
99/8688
100/8688
101/8688
102/8688
103/8688
104/8688
105/8688
106/8688
107/8688
108/8688
109/8688
110/8688
111/8688
112/8688
113/8688
114/8688
115/8688
116/8688
117/8688
118/8688
119/8688
120/8688
121/8688
122/8688
123/8688
124/8688
125/8688
126/8688
127/8688
128/8688
129/8688
130/8688
131/8688
132/8688
133/8688
134/8688
135/8688
136/8688
137/8688
138/8688
139/8688
140/8688
141/8688
142/8688
143/8688
144/8688
145/8688
146/8688
147/8688
148/8688
149/8688
150/8688
151/8688
152/8688
153/8688
154/8688
155/8688
156/8688
157/8688
158/8688
159/8688
160/8688
161/8688
162/8688
163/8688
164/8688
165/8688
166/8688
167/8688
168/8688
169/8688
170/8688
171/8688
172/8688
173/8688
174/8688
175/8688
176/8688
177/8688
178/8688
179/8688
180/8688
181/8688
182/8688
183/8688
184/8688
185/8688
186/8688
187/8688
188/8688
189/8688
190/8688
191/8688
192/8688
193/8688
194/8688
195/8688
196/8688
197/8688
198/8688
199/8688
200/8688
201/8688
202/8688
203/8688
204/8688
205/8688
206/8688
207/8688
208/8688
209/8688
210/8688
211/8688
212/8688
213/8688
214/8688
215/8688
216/8688
217/8688
218/8688
219/8688
220/8688
221/8688
222/8688
223/8688
224/8688
225/8688
226/8688
227/8688
228/8688
229/8688
230/8688
231/8688
232/8688
233/8688
234/8688
235/8688
236/8688
237/8688
238/8688
239/8688
240/8688
241/8688
242/8688
243/8688
244/8688
245/8688
246/8688
247/8688
248/8688
249/8688
250/8688
251/8688
252/8688
253/8688
254/8688
255/8688
256/8688
257/8688
258/8688
259/8688
260/8688
261/8688
262/8688
263/8688
264/8688
265/8688
266/8688
267/8688
268/8688
269/8688
270/8688
271/8688
272/8688
273/8688
274/8688
275/8688
276/8688
277/8688
278/8688
279/8688
280/8688
281/8688
282/8688
283/8688
284/8688
285/8688
286/8688
287/8688
288/8688
289/8688
290/8688
291/8688
292/8688
293/8688
294/8688
295/8688
296/8688
297/8688
298/8688
299/8688
300/8688
301/8688
302/8688
303/8688
304/8688
305/8688
306/8688
307/8688
308/8688
309/8688
310/8688
311/8688
312/8688
313/8688
314/8688
315/8688
316/8688
317/8688
318/8688
319/8688
320/8688
321/8688
322/8688
323/8688
324/8688
325/8688
326/8688
327/8688
328/8688
329/8688
330/8688
331/8688
332/8688
333/8688
334/8688
335/8688
336/8688
337/8688
338/8688
339/8688
340/8688
341/8688
342/8688
343/8688
344/8688
345/8688
346/8688
347/8688
348/8688
349/8688
350/8688
351/8688
352/8688
353/8688
354/8688
355/8688
356/8688
357/8688
358/8688
359/8688
360/8688
361/8688
362/8688
363/8688
364/8688
365/8688
366/8688
367/8688
368/8688
369/8688
370/8688
371/8688
372/8688
373/8688
374/8688
375/8688
376/8688
377/8688
378/8688
379/8688
380/8688
381/8688
382/8688
383/8688
384/8688
385/8688
386/8688
387/8688
388/8688
389/8688
390/8688
391/8688
392/8688
393/8688
394/8688
395/8688
396/8688
397/8688
398/8688
399/8688
400/8688
401/8688
402/8688
403/8688
404/8688
405/8688
406/8688
407/8688
408/8688
409/8688
410/8688
411/8688
412/8688
413/8688
414/8688
415/8688
416/8688
417/8688
418/8688
419/8688
420/8688
421/8688
422/8688
423/8688
424/8688
425/8688
426/8688
427/8688
428/8688
429/8688
430/8688
431/8688
432/8688
433/8688
434/8688
435/8688
436/8688
437/8688
438/8688
439/8688
440/8688
441/8688
442/8688
443/8688
444/8688
445/8688
446/8688
447/8688
448/8688
449/8688
450/8688
451/8688
452/8688
453/8688
454/8688
455/8688
456/8688
457/8688
458/8688
459/8688
460/8688
461/8688
462/8688
463/8688
464/8688
465/8688
466/8688
467/8688
468/8688
469/8688
470/8688
471/8688
472/8688
473/8688
474/8688
475/8688
476/8688
477/8688
478/8688
479/8688
480/8688
481/8688
482/8688
483/8688
484/8688
485/8688
486/8688
487/8688
488/8688
489/8688
490/8688
491/8688
492/8688
493/8688
494/8688
495/8688
496/8688
497/8688
498/8688
499/8688
500/8688
501/8688
502/8688
503/8688
504/8688
505/8688
506/8688
507/8688
508/8688
509/8688
510/8688
511/8688
512/8688
513/8688
514/8688
515/8688
516/8688
517/8688
518/8688
519/8688
520/8688
521/8688
522/8688
523/8688
524/8688
525/8688
526/8688
527/8688
528/8688
529/8688
530/8688
531/8688
532/8688
533/8688
534/8688
535/8688
536/8688
537/8688
538/8688
539/8688
540/8688
541/8688
542/8688
543/8688
544/8688
545/8688
546/8688
547/8688
548/8688
549/8688
550/8688
551/8688
552/8688
553/8688
554/8688
555/8688
556/8688
557/8688
558/8688
559/8688
560/8688
561/8688
562/8688
563/8688
564/8688
565/8688
566/8688
567/8688
568/8688
error: http://ufcstats.com/fight-details/b87d6f71d901355b
570/8688
571/8688
572/8688
573/8688
574/8688
575/8688
576/8688
577/8688
578/8688
579/8688
580/8688
581/8688
582/8688
583/8688
584/8688
585/8688
586/8688
587/8688
588/8688
589/8688
590/8688
591/8688
592/8688
593/8688
594/8688
595/8688
596/8688
597/8688
598/8688
599/8688
600/8688
601/8688
602/8688
603/8688
604/8688
605/8688
606/8688
607/8688
608/8688
609/8688
610/8688
611/8688
612/8688
613/8688
614/8688
615/8688
616/8688
617/8688
618/8688
619/8688
620/8688
621/8688
622/8688
623/8688
624/8688
625/8688
626/8688
627/8688
628/8688
629/8688
630/8688
631/8688
632/8688
633/8688
634/8688
635/8688
636/8688
637/8688
638/8688
639/8688
640/8688
641/8688
642/8688
643/8688
644/8688
645/8688
646/8688
647/8688
648/8688
649/8688
650/8688
651/8688
652/8688
653/8688
654/8688
655/8688
656/8688
657/8688
658/8688
659/8688
660/8688
661/8688
662/8688
663/8688
664/8688
665/8688
666/8688
667/8688
668/8688
669/8688
670/8688
671/8688
672/8688
673/8688
674/8688
675/8688
676/8688
677/8688
678/8688
679/8688
680/8688
681/8688
682/8688
683/8688
684/8688
685/8688
686/8688
687/8688
688/8688
689/8688
690/8688
691/8688
692/8688
693/8688
694/8688
695/8688
696/8688
697/8688
698/8688
699/8688
700/8688
701/8688
702/8688
703/8688
704/8688
705/8688
706/8688
707/8688
708/8688
709/8688
710/8688
711/8688
712/8688
713/8688
714/8688
715/8688
716/8688
717/8688
718/8688
719/8688
720/8688
721/8688
722/8688
723/8688
724/8688
725/8688
726/8688
727/8688
728/8688
729/8688
730/8688
731/8688
732/8688
733/8688
734/8688
735/8688
736/8688
737/8688
738/8688
739/8688
740/8688
741/8688
742/8688
743/8688
744/8688
745/8688
746/8688
747/8688
748/8688
749/8688
750/8688
751/8688
752/8688
753/8688
754/8688
755/8688
756/8688
757/8688
758/8688
759/8688
760/8688
761/8688
762/8688
763/8688
764/8688
765/8688
766/8688
767/8688
768/8688
769/8688
770/8688
771/8688
772/8688
773/8688
774/8688
775/8688
776/8688
777/8688
778/8688
779/8688
780/8688
781/8688
782/8688
783/8688
784/8688
785/8688
786/8688
787/8688
788/8688
789/8688
790/8688
791/8688
792/8688
793/8688
794/8688
795/8688
796/8688
797/8688
798/8688
799/8688
800/8688
801/8688
802/8688
803/8688
804/8688
805/8688
806/8688
807/8688
808/8688
809/8688
810/8688
811/8688
812/8688
813/8688
814/8688
815/8688
816/8688
817/8688
818/8688
819/8688
820/8688
821/8688
822/8688
823/8688
824/8688
825/8688
826/8688
827/8688
828/8688
829/8688
830/8688
831/8688
832/8688
833/8688
834/8688
835/8688
836/8688
837/8688
838/8688
839/8688
840/8688
841/8688
842/8688
843/8688
844/8688
845/8688
846/8688
847/8688
848/8688
849/8688
850/8688
851/8688
852/8688
853/8688
854/8688
855/8688
856/8688
857/8688
858/8688
859/8688
860/8688
861/8688
862/8688
863/8688
864/8688
865/8688
866/8688
867/8688
868/8688
869/8688
870/8688
871/8688
872/8688
873/8688
874/8688
875/8688
876/8688
877/8688
878/8688
879/8688
880/8688
881/8688
882/8688
883/8688
884/8688
885/8688
886/8688
887/8688
888/8688
889/8688
890/8688
891/8688
892/8688
893/8688
894/8688
895/8688
896/8688
897/8688
898/8688
899/8688
900/8688
901/8688
902/8688
903/8688
904/8688
905/8688
906/8688
907/8688
908/8688
909/8688
910/8688
911/8688
912/8688
913/8688
914/8688
915/8688
916/8688
917/8688
918/8688
919/8688
920/8688
921/8688
922/8688
923/8688
924/8688
925/8688
926/8688
927/8688
928/8688
929/8688
930/8688
931/8688
932/8688
933/8688
934/8688
935/8688
936/8688
937/8688
938/8688
939/8688
940/8688
941/8688
942/8688
943/8688
944/8688
945/8688
946/8688
947/8688
948/8688
949/8688
950/8688
951/8688
952/8688
953/8688
954/8688
955/8688
956/8688
957/8688
958/8688
959/8688
960/8688
961/8688
962/8688
963/8688
964/8688
965/8688
966/8688
967/8688
968/8688
969/8688
970/8688
971/8688
972/8688
973/8688
974/8688
975/8688
976/8688
977/8688
978/8688
979/8688
980/8688
981/8688
982/8688
983/8688
984/8688
985/8688
986/8688
987/8688
988/8688
989/8688
990/8688
991/8688
992/8688
993/8688
994/8688
995/8688
996/8688
997/8688
998/8688
999/8688
1000/8688
1001/8688
1002/8688
1003/8688
1004/8688
1005/8688
1006/8688
1007/8688
1008/8688
1009/8688
1010/8688
1011/8688
1012/8688
1013/8688
1014/8688
1015/8688
1016/8688
1017/8688
1018/8688
1019/8688
1020/8688
1021/8688
1022/8688
1023/8688
1024/8688
1025/8688
1026/8688
1027/8688
1028/8688
1029/8688
1030/8688
1031/8688
1032/8688
1033/8688
1034/8688
1035/8688
1036/8688
1037/8688
1038/8688
1039/8688
1040/8688
1041/8688
1042/8688
1043/8688
1044/8688
1045/8688
1046/8688
1047/8688
1048/8688
1049/8688
1050/8688
1051/8688
1052/8688
1053/8688
1054/8688
1055/8688
1056/8688
1057/8688
1058/8688
1059/8688
1060/8688
1061/8688
1062/8688
1063/8688
1064/8688
1065/8688
1066/8688
1067/8688
1068/8688
1069/8688
1070/8688
1071/8688
1072/8688
1073/8688
1074/8688
1075/8688
1076/8688
1077/8688
1078/8688
1079/8688
1080/8688
1081/8688
1082/8688
1083/8688
1084/8688
1085/8688
1086/8688
1087/8688
1088/8688
1089/8688
1090/8688
1091/8688
1092/8688
1093/8688
1094/8688
1095/8688
1096/8688
1097/8688
1098/8688
1099/8688
1100/8688
1101/8688
1102/8688
1103/8688
1104/8688
1105/8688
1106/8688
1107/8688
1108/8688
1109/8688
1110/8688
1111/8688
1112/8688
1113/8688
1114/8688
1115/8688
1116/8688
1117/8688
1118/8688
1119/8688
1120/8688
1121/8688
1122/8688
1123/8688
1124/8688
1125/8688
1126/8688
1127/8688
1128/8688
1129/8688
1130/8688
1131/8688
1132/8688
1133/8688
1134/8688
1135/8688
1136/8688
1137/8688
1138/8688
1139/8688
1140/8688
1141/8688
1142/8688
1143/8688
1144/8688
1145/8688
1146/8688
1147/8688
1148/8688
1149/8688
1150/8688
1151/8688
1152/8688
1153/8688
1154/8688
1155/8688
1156/8688
1157/8688
1158/8688
1159/8688
1160/8688
1161/8688
1162/8688
1163/8688
1164/8688
1165/8688
1166/8688
1167/8688
1168/8688
1169/8688
1170/8688
1171/8688
1172/8688
1173/8688
1174/8688
1175/8688
1176/8688
1177/8688
1178/8688
1179/8688
1180/8688
1181/8688
1182/8688
1183/8688
1184/8688
1185/8688
1186/8688
1187/8688
1188/8688
1189/8688
1190/8688
1191/8688
1192/8688
1193/8688
1194/8688
1195/8688
1196/8688
1197/8688
1198/8688
1199/8688
1200/8688
1201/8688
1202/8688
1203/8688
1204/8688
1205/8688
1206/8688
1207/8688
1208/8688
1209/8688
1210/8688
1211/8688
1212/8688
1213/8688
1214/8688
1215/8688
1216/8688
1217/8688
1218/8688
1219/8688
1220/8688
1221/8688
1222/8688
1223/8688
1224/8688
1225/8688
1226/8688
1227/8688
1228/8688
1229/8688
1230/8688
1231/8688
1232/8688
1233/8688
1234/8688
1235/8688
1236/8688
1237/8688
1238/8688
1239/8688
1240/8688
1241/8688
1242/8688
1243/8688
1244/8688
1245/8688
1246/8688
1247/8688
1248/8688
1249/8688
1250/8688
1251/8688
1252/8688
1253/8688
1254/8688
1255/8688
1256/8688
1257/8688
1258/8688
1259/8688
1260/8688
1261/8688
1262/8688
1263/8688
1264/8688
1265/8688
1266/8688
1267/8688
1268/8688
1269/8688
1270/8688
1271/8688
1272/8688
1273/8688
1274/8688
1275/8688
1276/8688
1277/8688
1278/8688
1279/8688
1280/8688
1281/8688
1282/8688
1283/8688
1284/8688
1285/8688
1286/8688
1287/8688
1288/8688
1289/8688
1290/8688
1291/8688
1292/8688
1293/8688
1294/8688
1295/8688
1296/8688
1297/8688
1298/8688
1299/8688
1300/8688
1301/8688
1302/8688
1303/8688
1304/8688
1305/8688
1306/8688
1307/8688
1308/8688
1309/8688
1310/8688
1311/8688
1312/8688
1313/8688
1314/8688
1315/8688
1316/8688
1317/8688
1318/8688
1319/8688
1320/8688
1321/8688
1322/8688
1323/8688
1324/8688
1325/8688
1326/8688
1327/8688
1328/8688
1329/8688
1330/8688
1331/8688
1332/8688
1333/8688
1334/8688
1335/8688
1336/8688
1337/8688
1338/8688
1339/8688
1340/8688
1341/8688
1342/8688
1343/8688
1344/8688
1345/8688
1346/8688
1347/8688
1348/8688
1349/8688
1350/8688
1351/8688
1352/8688
1353/8688
1354/8688
1355/8688
1356/8688
1357/8688
1358/8688
1359/8688
1360/8688
1361/8688
1362/8688
1363/8688
1364/8688
1365/8688
1366/8688
1367/8688
1368/8688
1369/8688
1370/8688
1371/8688
1372/8688
1373/8688
1374/8688
1375/8688
1376/8688
1377/8688
1378/8688
1379/8688
1380/8688
1381/8688
1382/8688
1383/8688
1384/8688
1385/8688
1386/8688
1387/8688
1388/8688
1389/8688
1390/8688
1391/8688
1392/8688
1393/8688
1394/8688
1395/8688
1396/8688
1397/8688
1398/8688
1399/8688
1400/8688
1401/8688
1402/8688
1403/8688
1404/8688
1405/8688
1406/8688
1407/8688
1408/8688
1409/8688
1410/8688
1411/8688
1412/8688
1413/8688
1414/8688
1415/8688
1416/8688
1417/8688
1418/8688
1419/8688
1420/8688
1421/8688
1422/8688
1423/8688
1424/8688
1425/8688
1426/8688
1427/8688
1428/8688
1429/8688
1430/8688
1431/8688
1432/8688
1433/8688
1434/8688
1435/8688
1436/8688
1437/8688
1438/8688
1439/8688
1440/8688
1441/8688
1442/8688
1443/8688
1444/8688
1445/8688
1446/8688
1447/8688
1448/8688
1449/8688
1450/8688
1451/8688
1452/8688
1453/8688
1454/8688
1455/8688
1456/8688
1457/8688
1458/8688
1459/8688
1460/8688
1461/8688
1462/8688
1463/8688
1464/8688
1465/8688
1466/8688
1467/8688
1468/8688
1469/8688
1470/8688
1471/8688
1472/8688
1473/8688
1474/8688
1475/8688
1476/8688
1477/8688
1478/8688
1479/8688
1480/8688
1481/8688
1482/8688
1483/8688
1484/8688
1485/8688
1486/8688
1487/8688
1488/8688
1489/8688
1490/8688
1491/8688
1492/8688
1493/8688
1494/8688
1495/8688
1496/8688
1497/8688
1498/8688
1499/8688
1500/8688
1501/8688
1502/8688
1503/8688
1504/8688
1505/8688
1506/8688
1507/8688
1508/8688
1509/8688
1510/8688
1511/8688
1512/8688
1513/8688
1514/8688
1515/8688
1516/8688
1517/8688
1518/8688
1519/8688
1520/8688
1521/8688
1522/8688
1523/8688
1524/8688
1525/8688
1526/8688
1527/8688
1528/8688
1529/8688
1530/8688
1531/8688
1532/8688
1533/8688
1534/8688
1535/8688
1536/8688
1537/8688
1538/8688
1539/8688
1540/8688
1541/8688
1542/8688
1543/8688
1544/8688
1545/8688
1546/8688
1547/8688
1548/8688
1549/8688
1550/8688
1551/8688
1552/8688
1553/8688
1554/8688
1555/8688
1556/8688
1557/8688
1558/8688
1559/8688
1560/8688
1561/8688
1562/8688
1563/8688
error: http://ufcstats.com/fight-details/3387f430abb7e39f
1565/8688
1566/8688
1567/8688
1568/8688
error: http://ufcstats.com/fight-details/e3aad51099a23ba4
1570/8688
1571/8688
1572/8688
1573/8688
1574/8688
1575/8688
1576/8688
1577/8688
1578/8688
1579/8688
1580/8688
1581/8688
1582/8688
1583/8688
1584/8688
1585/8688
1586/8688
1587/8688
1588/8688
1589/8688
1590/8688
1591/8688
1592/8688
1593/8688
1594/8688
1595/8688
1596/8688
1597/8688
1598/8688
1599/8688
1600/8688
1601/8688
1602/8688
1603/8688
1604/8688
1605/8688
1606/8688
1607/8688
1608/8688
1609/8688
1610/8688
1611/8688
1612/8688
1613/8688
1614/8688
1615/8688
1616/8688
1617/8688
1618/8688
1619/8688
1620/8688
1621/8688
1622/8688
1623/8688
1624/8688
1625/8688
1626/8688
1627/8688
1628/8688
1629/8688
1630/8688
1631/8688
1632/8688
1633/8688
1634/8688
1635/8688
1636/8688
1637/8688
1638/8688
1639/8688
1640/8688
1641/8688
1642/8688
1643/8688
1644/8688
1645/8688
1646/8688
1647/8688
1648/8688
1649/8688
1650/8688
1651/8688
1652/8688
1653/8688
1654/8688
1655/8688
1656/8688
1657/8688
1658/8688
1659/8688
1660/8688
1661/8688
1662/8688
1663/8688
1664/8688
1665/8688
1666/8688
1667/8688
1668/8688
1669/8688
1670/8688
1671/8688
1672/8688
1673/8688
1674/8688
1675/8688
1676/8688
1677/8688
1678/8688
1679/8688
1680/8688
1681/8688
1682/8688
1683/8688
1684/8688
1685/8688
1686/8688
1687/8688
1688/8688
1689/8688
1690/8688
1691/8688
1692/8688
1693/8688
1694/8688
1695/8688
1696/8688
1697/8688
1698/8688
1699/8688
1700/8688
1701/8688
1702/8688
1703/8688
1704/8688
1705/8688
1706/8688
1707/8688
1708/8688
1709/8688
1710/8688
1711/8688
1712/8688
1713/8688
1714/8688
1715/8688
1716/8688
1717/8688
1718/8688
1719/8688
1720/8688
1721/8688
1722/8688
1723/8688
1724/8688
1725/8688
1726/8688
1727/8688
1728/8688
1729/8688
1730/8688
1731/8688
1732/8688
1733/8688
1734/8688
1735/8688
1736/8688
1737/8688
1738/8688
1739/8688
1740/8688
1741/8688
1742/8688
1743/8688
1744/8688
1745/8688
1746/8688
1747/8688
1748/8688
1749/8688
1750/8688
1751/8688
1752/8688
1753/8688
1754/8688
1755/8688
1756/8688
1757/8688
1758/8688
1759/8688
1760/8688
1761/8688
1762/8688
1763/8688
1764/8688
1765/8688
1766/8688
1767/8688
1768/8688
1769/8688
1770/8688
1771/8688
1772/8688
1773/8688
1774/8688
1775/8688
1776/8688
1777/8688
1778/8688
1779/8688
1780/8688
1781/8688
1782/8688
1783/8688
1784/8688
1785/8688
1786/8688
1787/8688
1788/8688
1789/8688
1790/8688
1791/8688
1792/8688
1793/8688
1794/8688
1795/8688
1796/8688
1797/8688
1798/8688
1799/8688
1800/8688
1801/8688
1802/8688
1803/8688
1804/8688
1805/8688
1806/8688
1807/8688
1808/8688
1809/8688
1810/8688
1811/8688
1812/8688
1813/8688
1814/8688
1815/8688
1816/8688
1817/8688
1818/8688
1819/8688
1820/8688
1821/8688
1822/8688
1823/8688
1824/8688
1825/8688
1826/8688
1827/8688
1828/8688
1829/8688
1830/8688
1831/8688
1832/8688
1833/8688
1834/8688
1835/8688
1836/8688
1837/8688
1838/8688
1839/8688
1840/8688
1841/8688
1842/8688
1843/8688
1844/8688
1845/8688
1846/8688
1847/8688
1848/8688
1849/8688
1850/8688
1851/8688
1852/8688
1853/8688
1854/8688
1855/8688
1856/8688
1857/8688
1858/8688
1859/8688
1860/8688
1861/8688
1862/8688
1863/8688
1864/8688
1865/8688
1866/8688
1867/8688
1868/8688
1869/8688
1870/8688
1871/8688
1872/8688
1873/8688
1874/8688
1875/8688
1876/8688
1877/8688
1878/8688
1879/8688
1880/8688
1881/8688
1882/8688
1883/8688
1884/8688
1885/8688
1886/8688
1887/8688
1888/8688
1889/8688
1890/8688
1891/8688
1892/8688
1893/8688
1894/8688
1895/8688
1896/8688
1897/8688
1898/8688
1899/8688
1900/8688
1901/8688
1902/8688
1903/8688
1904/8688
1905/8688
1906/8688
1907/8688
1908/8688
1909/8688
1910/8688
1911/8688
1912/8688
1913/8688
1914/8688
1915/8688
1916/8688
1917/8688
1918/8688
1919/8688
1920/8688
1921/8688
1922/8688
1923/8688
1924/8688
1925/8688
1926/8688
1927/8688
1928/8688
1929/8688
1930/8688
1931/8688
1932/8688
1933/8688
1934/8688
1935/8688
1936/8688
1937/8688
1938/8688
1939/8688
1940/8688
1941/8688
1942/8688
1943/8688
1944/8688
1945/8688
1946/8688
1947/8688
1948/8688
1949/8688
1950/8688
1951/8688
1952/8688
1953/8688
1954/8688
1955/8688
1956/8688
1957/8688
1958/8688
1959/8688
1960/8688
1961/8688
1962/8688
1963/8688
1964/8688
1965/8688
1966/8688
1967/8688
1968/8688
1969/8688
1970/8688
1971/8688
1972/8688
1973/8688
1974/8688
1975/8688
1976/8688
1977/8688
1978/8688
1979/8688
1980/8688
1981/8688
1982/8688
1983/8688
1984/8688
1985/8688
1986/8688
1987/8688
1988/8688
1989/8688
1990/8688
1991/8688
1992/8688
1993/8688
1994/8688
1995/8688
1996/8688
1997/8688
1998/8688
1999/8688
2000/8688
2001/8688
2002/8688
2003/8688
2004/8688
2005/8688
2006/8688
2007/8688
2008/8688
2009/8688
2010/8688
2011/8688
2012/8688
2013/8688
2014/8688
2015/8688
2016/8688
2017/8688
2018/8688
2019/8688
2020/8688
2021/8688
2022/8688
2023/8688
2024/8688
2025/8688
2026/8688
2027/8688
2028/8688
2029/8688
2030/8688
2031/8688
2032/8688
2033/8688
2034/8688
2035/8688
2036/8688
2037/8688
2038/8688
2039/8688
2040/8688
2041/8688
2042/8688
2043/8688
2044/8688
2045/8688
2046/8688
2047/8688
2048/8688
2049/8688
2050/8688
2051/8688
2052/8688
2053/8688
2054/8688
2055/8688
2056/8688
2057/8688
2058/8688
2059/8688
2060/8688
2061/8688
2062/8688
2063/8688
2064/8688
2065/8688
2066/8688
2067/8688
2068/8688
2069/8688
2070/8688
2071/8688
2072/8688
2073/8688
2074/8688
2075/8688
2076/8688
2077/8688
2078/8688
2079/8688
2080/8688
2081/8688
2082/8688
2083/8688
2084/8688
2085/8688
2086/8688
2087/8688
2088/8688
2089/8688
2090/8688
2091/8688
2092/8688
2093/8688
2094/8688
2095/8688
2096/8688

In [2]:
import pandas as pd

wins = pd.read_csv('temp_wins.csv')
fights = pd.read_csv('fights_temp.csv')

In [3]:
wins.head(3)

                                           fight_url            winner
0  http://ufcstats.com/fight-details/70f1621080b3...   Sean Strickland
1  http://ufcstats.com/fight-details/c85b53086114...        Joshua Van
2  http://ufcstats.com/fight-details/22ba4f1b0aaf...  Alexander Volkov

In [4]:
fights.head(3)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0
1,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Flyweight,KO/TKO Punches,5,1:32,2,0,131,55,1,8,2,0
2,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/22ba4f1b0aaf...,Alexander Volkov,Waldo Cortes Acosta,Heavyweight,U-DEC,3,5:00,0,0,88,54,0,0,0,0

In [5]:
final_fights = fights.merge(wins, on='fight_url',how='left')

In [6]:
final_fights.head(4)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,winner
0,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0,Sean Strickland
1,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Flyweight,KO/TKO Punches,5,1:32,2,0,131,55,1,8,2,0,Joshua Van
2,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/22ba4f1b0aaf...,Alexander Volkov,Waldo Cortes Acosta,Heavyweight,U-DEC,3,5:00,0,0,88,54,0,0,0,0,Alexander Volkov
3,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/845b8653f9cf...,Sean Brady,Joaquin Buckley,Welterweight,U-DEC,3,5:00,0,0,77,5,4,0,0,0,Sean Brady

In [21]:
final_fights.isnull().sum()

event_name            0
event_id              0
fight_url             0
fighter_1             0
fighter_2             0
weight_class          0
method                0
round                 0
time                  0
fighter1_kd           0
fighter2_kd           0
fighter1_strikes      0
fighter2_strikes      0
fighter1_td           0
fighter2_td           0
fighter1_sub          0
fighter2_sub          0
winner              161
dtype: int64

In [22]:
# null είναι τα draws αρα :
final_fights['winner'] = final_fights['winner'].fillna('draw')

In [24]:
final_fights.shape

(8688, 18)

In [23]:
final_fights.head(2)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,winner
0,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Middleweight,S-DEC,5,5:00,0,0,123,98,0,9,0,0,Sean Strickland
1,UFC 328: Chimaev vs. Strickland,773,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Flyweight,KO/TKO Punches,5,1:32,2,0,131,55,1,8,2,0,Joshua Van

In [25]:
final_fights['fight_id'] = [i for i in range(8688,0,-1)]

In [27]:
final_fights.tail(1)

,event_name,event_id,fight_url,fighter_1,fighter_2,weight_class,method,round,time,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,winner,fight_id
8687,UFC 2: No Way Out,1,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,Open Weight,SUB Guillotine Choke,1,0:20,0,0,1,0,1,0,1,0,Scott Morris,1

In [29]:
final_fights = final_fights[['fight_id','fight_url','fighter_1','fighter_2','winner','weight_class','method','round','time',
                             'event_name', 'event_id', 'fighter1_kd', 'fighter2_kd',
       'fighter1_strikes', 'fighter2_strikes', 'fighter1_td', 'fighter2_td',
       'fighter1_sub', 'fighter2_sub']]

In [30]:
final_fights.shape

(8688, 19)

In [40]:
import numpy as np
# θα πάρω τα -- σθμβολα που υπάροχυν και θα τα κανω ναλ
final_fights['fighter2_kd'] = final_fights['fighter2_kd'].replace('--', np.nan)
final_fights['fighter1_kd'] = final_fights['fighter1_kd'].replace('--', np.nan)
final_fights['fighter1_strikes'] = final_fights['fighter1_strikes'].replace('--', np.nan)
final_fights['fighter2_strikes'] = final_fights['fighter2_strikes'].replace('--', np.nan)
final_fights['fighter1_td'] = final_fights['fighter1_td'].replace('--', np.nan)
final_fights['fighter2_td'] = final_fights['fighter2_td'].replace('--', np.nan)
final_fights['fighter1_sub'] = final_fights['fighter1_sub'].replace('--', np.nan)
final_fights['fighter2_sub'] = final_fights['fighter2_sub'].replace('--', np.nan)

In [41]:
final_fights.to_csv('fights.csv',index=False)

In [42]:
final_fights.info(
)

<class 'pandas.DataFrame'>
RangeIndex: 8688 entries, 0 to 8687
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fight_id          8688 non-null   int64
 1   fight_url         8688 non-null   str
 2   fighter_1         8688 non-null   str
 3   fighter_2         8688 non-null   str
 4   winner            8688 non-null   str
 5   weight_class      8688 non-null   str
 6   method            8688 non-null   str
 7   round             8688 non-null   int64
 8   time              8688 non-null   str
 9   event_name        8688 non-null   str
 10  event_id          8688 non-null   int64
 11  fighter1_kd       8667 non-null   str
 12  fighter2_kd       8667 non-null   str
 13  fighter1_strikes  8667 non-null   str
 14  fighter2_strikes  8667 non-null   str
 15  fighter1_td       8667 non-null   str
 16  fighter2_td       8667 non-null   str
 17  fighter1_sub      8667 non-null   str
 18  fighter2_sub      8667 non-null   str
dtypes: int64(3), str(16)
memory usage: 1.3 MB

In [43]:
final_fights['fighter1_sub'].unique()

<StringArray>
['0', '2', '1', '4', '5', '3', '6', '7', '8', '10', '9', nan]
Length: 12, dtype: str